artifacts_root: artifacts
data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/entbappy/Branching-tutorial/blob/master/Chicken-fecal-images.zip
  local_data_file: artifacts/data_ingestion/Chicken-fecal-images.zip
  unzip_dir: artifacts/data_ingestion/unzipped_data  # Add this line
